### An example

Link to the Quickstart tutorial: https://numpy.org/doc/stable/user/quickstart.html

Link to the basics for beginner: https://numpy.org/doc/stable/user/absolute_beginners.html

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)

In [2]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int32'

In [6]:
a.itemsize

4

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([6,7,8])

In [10]:
b

array([6, 7, 8])

In [11]:
type(b)

numpy.ndarray

### Array Creation

##### Create normal array

In [12]:
import numpy as np
a = np.array([2,3,4])

In [13]:
a

array([2, 3, 4])

In [14]:
a.dtype

dtype('int32')

In [15]:
b = np.array([1.2, 3.5, 2.1])

In [16]:
b

array([1.2, 3.5, 2.1])

In [17]:
b.dtype

dtype('float64')

##### Create array with complex numbers

In [18]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

In [19]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

##### Create array with initial numbers

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [26]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

To create sequences of numbers, NumPy provides the `arange` function which is analogous to the Python built-in `range`, but returns an array.

In [1]:
import numpy as np

In [2]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [3]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When `arange` is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function `linspace` that receives as an argument the number of elements that we want, instead of the step:

In [4]:
np.linspace(5,20,100)

array([ 5.        ,  5.15151515,  5.3030303 ,  5.45454545,  5.60606061,
        5.75757576,  5.90909091,  6.06060606,  6.21212121,  6.36363636,
        6.51515152,  6.66666667,  6.81818182,  6.96969697,  7.12121212,
        7.27272727,  7.42424242,  7.57575758,  7.72727273,  7.87878788,
        8.03030303,  8.18181818,  8.33333333,  8.48484848,  8.63636364,
        8.78787879,  8.93939394,  9.09090909,  9.24242424,  9.39393939,
        9.54545455,  9.6969697 ,  9.84848485, 10.        , 10.15151515,
       10.3030303 , 10.45454545, 10.60606061, 10.75757576, 10.90909091,
       11.06060606, 11.21212121, 11.36363636, 11.51515152, 11.66666667,
       11.81818182, 11.96969697, 12.12121212, 12.27272727, 12.42424242,
       12.57575758, 12.72727273, 12.87878788, 13.03030303, 13.18181818,
       13.33333333, 13.48484848, 13.63636364, 13.78787879, 13.93939394,
       14.09090909, 14.24242424, 14.39393939, 14.54545455, 14.6969697 ,
       14.84848485, 15.        , 15.15151515, 15.3030303 , 15.45

In [5]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [6]:
from numpy import pi

In [7]:
x = np.linspace(0,2*pi,100)

In [8]:
f = np.sin(x)

In [9]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [10]:
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [11]:
B = np.arange(3)

In [12]:
B

array([0, 1, 2])

##### Function and Universal Function

In [13]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

##### Indexing, Slicing and Iterating

In [14]:
a = np.arange(10)**3

In [15]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [16]:
a.dtype.name

'int32'

In [17]:
a.ndim

1

In [18]:
a.size

10

In [1]:
import numpy as np

In [2]:
a = np.arange(10)**3

In [3]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [4]:
a[0]

0

In [5]:
a[2]

8

In [6]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [7]:
print(a[:5])

[ 0  1  8 27 64]


In [8]:
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000

In [9]:
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [11]:
# reverse an array using index slicing
b = a[::-1]

In [12]:
b

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [13]:
b = a[:-1:1]

In [14]:
b

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512], dtype=int32)

In [15]:
for i in a:
    print(i**(1/3))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [16]:
for i in a:
    print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [17]:
def f(x,y):
    return 10*x + y
b = np.fromfunction(f,(5,4),dtype=int)

In [18]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [20]:
c = np.fromfunction(lambda i,j: 10*i + j,(5,4), dtype = int)
c

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [21]:
c[2,3]

23

In [22]:
c[1,:]

array([10, 11, 12, 13])

In [23]:
c[:,1]

array([ 1, 11, 21, 31, 41])

In [24]:
c[1:5,1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43]])

In [25]:
c[-1]

array([40, 41, 42, 43])

In [27]:
c[:,-1]

array([ 3, 13, 23, 33, 43])