### EXERCISE 1 - Element-wise addition of 2 numpy arrays

Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?

In [1]:
import numpy as np

a = np.array([[1,2,3], [2,3,4]])
b = np.array([[3,2,5], [7,6,6]])

c = a + b

print("a:")
print(a)
print("b:")
print(b)
print("Element-wise addition (c[i][j] = a[i][j] + b[i][j]) of a and b: ")
print(c)

a:
[[1 2 3]
 [2 3 4]]
b:
[[3 2 5]
 [7 6 6]]
Element-wise addition (c[i][j] = a[i][j] + b[i][j]) of a and b: 
[[ 4  4  8]
 [ 9  9 10]]
