### EXERCISE 16 - Matrix Multiplication

Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)

In [1]:
import numpy as np

In [2]:
a = np.array([[2,3,4], [3,4,2]])

In [3]:
b = np.array([[3,2], [4,3], [1,3]])

In [6]:
print(a)

[[2 3 4]
 [3 4 2]]


In [7]:
print(b)

[[3 2]
 [4 3]
 [1 3]]


In [9]:
mulp = a@b

In [10]:
print(mulp)

[[22 25]
 [27 24]]
