### EXERCISE 20 - Generating the array element indexes such that the array elements appear in ascending order

Output the array element indexes such that the array elements appear in the ascending order

In [1]:
import numpy as np

In [2]:
'''
Input: [10,1,5,2]
Output: [1 3 2 0]
'''

a = np.array([10,1,5,2])
asd = np.argsort(a, axis=0)

In [3]:
print(asd)

[1 3 2 0]


In [4]:
# descending order: reverse the asd array using array slicing [::-1]

des = asd[::-1]
print(des)

[0 2 3 1]


In [5]:
'''
Input:
[[10  1  5  2]
 [ 3  4  0  2]]
'''
b = np.array([[10,1,5,2], [3,4,0,2]])
print(b)

[[10  1  5  2]
 [ 3  4  0  2]]


In [6]:
# sort the elements in ascending order in vertical direction

ver = np.argsort(b, axis=0)
print(ver)

[[1 0 1 0]
 [0 1 0 1]]


In [7]:
hor = np.argsort(b, axis=1)
print(hor)

[[1 3 2 0]
 [2 3 0 1]]
