### EXERCISE 4 - Array re-dimensioning

Convert a 1-D array to a 3-D array

In [1]:
import numpy as np

a = np.arange(27)

print("1-D array a")
print(a)

print("3-D array a")
print(a.reshape(3,3,3))

1-D array a
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
3-D array a
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [2]:
b = np.array([x for x in range(18)])

print("1-D array b")
print(b)

print("3-D array b")
print(b.reshape(3,2,3))

1-D array b
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
3-D array b
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
