### EXERCISE 5 - Array datatype conversion

Convert all the elements of a numpy array from float to integer datatype

In [1]:
import numpy as np

a = np.array([[2.0, 3.1, 4.9], [1.5, 9.5, 8.3]])
print(a)
print(a.dtype)

[[2.  3.1 4.9]
 [1.5 9.5 8.3]]
float64


In [2]:
b = a.astype(int)
print(b)
print(b.dtype)

[[2 3 4]
 [1 9 8]]
int32
