### EXERCISE 6 - Obtaining Boolean Array from Binary Array

Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array

In [1]:
import numpy as np

a = np.array([[1,0,0], [0,1,0], [0,0,1]])
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [2]:
b = a.astype(bool)
print(b)

[[ True False False]
 [False  True False]
 [False False  True]]


In [3]:
c = np.array([[1,1,0], [0,1,1], [0,0,1]])
print(c)

[[1 1 0]
 [0 1 1]
 [0 0 1]]


In [4]:
d = c.astype(bool)
print(d)

[[ True  True False]
 [False  True  True]
 [False False  True]]
