### EXERCISE 8 - Vertically Stacking of Numpy Arrays

Stack 2 numpy arrays vertically i.e., 2 arrays having the same last dimension (number of columns in 2D arrays)

In [1]:
import numpy as np

a = np.array([[1,2,3], [3,2,1]])
b = np.array([[2,0,1], [3,4,5]])

In [2]:
a

array([[1, 2, 3],
       [3, 2, 1]])

In [3]:
b

array([[2, 0, 1],
       [3, 4, 5]])

In [5]:
c = np.vstack((a,b))

In [6]:
c

array([[1, 2, 3],
       [3, 2, 1],
       [2, 0, 1],
       [3, 4, 5]])