# Random Sampling

In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.3'

In [3]:
__author__ = 'kyubyong. longinglove@nate.com'

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

array([[ 0.13879034,  0.71300174],
       [ 0.08121322,  0.00393554],
       [ 0.02349471,  0.56677474]])

In [4]:
np.random.uniform(0, 1, (3, 2))

array([[0.3519202 , 0.77535886],
       [0.60151044, 0.88180825],
       [0.36808251, 0.84688174]])

Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

-0.00110028519551
0.999683483393


In [6]:
np.random.normal(loc=0.0, scale=1.0, size=(1000, 1000))

array([[ 0.29774236,  0.26312638,  1.23704563, ...,  0.53563168,
        -0.76199874, -0.32156677],
       [-2.44203089, -1.27803345, -0.35930573, ...,  1.70939689,
         1.79388815,  0.62585357],
       [ 0.19485474,  0.25321661, -0.6131681 , ...,  0.07196504,
         0.93241245,  0.73325884],
       ...,
       [-0.26589765,  0.15108255, -0.30559646, ..., -0.02564883,
        -0.3121279 , -0.96351946],
       [-0.46411366,  1.13212683,  0.52976357, ..., -0.43922705,
         0.33703044,  0.80219902],
       [-0.23596876, -0.28873573, -1.48847969, ..., -0.42892253,
         0.9929023 , -0.12354789]])

Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

array([[1, 3],
       [3, 0],
       [0, 0]])

In [9]:
np.random.randint(0, 4, size=(3,2), dtype=int)

array([[0, 3],
       [1, 0],
       [0, 0]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [3]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']


5 out of 10
2 out of 10
3 out of 10
5 out of 10
2 out of 10
5 out of 10
2 out of 10
2 out of 10
2 out of 10
5 out of 10


In [11]:
x = ['3 out of 10', '5 out of 10', '2 out of 10']

for i in range(10):
    print(np.random.choice(x, p=[.3, .5, .2]))

5 out of 10
5 out of 10
3 out of 10
5 out of 10
2 out of 10
5 out of 10
3 out of 10
5 out of 10
3 out of 10
3 out of 10


Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

array([5, 4, 0])

In [13]:
np.random.choice(10, 3, replace=False)

array([2, 8, 1])

## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [17]:
x = np.arange(10)

np.random.shuffle(x)
x

array([7, 9, 5, 6, 3, 2, 0, 1, 8, 4])

In [18]:
# Or
np.random.permutation(10)

array([1, 5, 3, 9, 0, 4, 7, 2, 8, 6])

## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [20]:
np.random.seed(10)